// Code generated by genum; DO NOT EDIT.
package enum

import (
	"database/sql/driver"
	"errors"
)

type enum struct{ string }

func (e enum) String() string {
	return e.string
}

func (e enum) Value() (driver.Value, error) {
	return e.string, nil
}

func (e *enum) Scan(raw any) error {
	value, ok := raw.(string)
	if !ok {
		return errors.New("raw.(string) type assertion failed") //nolint:goerr113
	}

	*e = enum{value}

	return nil
}

func (e enum) MarshalText() ([]byte, error) {
	return []byte(e.string), nil
}

func (e *enum) UnmarshalText(raw []byte) error {
	*e = enum{string(raw)}

	return nil
}
