// Code generated by genum; DO NOT EDIT.
package enum

import (
	"fmt"
	"slices"
	"strings"
)

type GameStatusEnum struct{ enum }

const GameStatus gameStatus = 0

// gameStatus выполняет роль пространства имён для значений GameStatusEnum.
type gameStatus int

func (gameStatus) Waiting() GameStatusEnum {
	return GameStatusEnum{enum{"waiting"}}
}

func (gameStatus) Active() GameStatusEnum {
	return GameStatusEnum{enum{"active"}}
}

func (gameStatus) Finished() GameStatusEnum {
	return GameStatusEnum{enum{"finished"}}
}

var gameStatusValues = []GameStatusEnum{ //nolint:gochecknoglobals
	GameStatus.Waiting(),
	GameStatus.Active(),
	GameStatus.Finished(),
}

// GameStatusValues возвращает перечень всех возможных значений для GameStatusEnum.
func GameStatusValues() []GameStatusEnum {
	return gameStatusValues
}

func ParseGameStatus(raw string) (GameStatusEnum, error) {
	switch raw {
	case "waiting":
		return GameStatus.Waiting(), nil
	case "active":
		return GameStatus.Active(), nil
	case "finished":
		return GameStatus.Finished(), nil
	default:
		return GameStatusEnum{}, fmt.Errorf("unsupported GameStatus value: %q", raw)
	}
}

func ParseGameStatusFold(raw string) (GameStatusEnum, error) {
	switch strings.ToLower(raw) {
	case "waiting":
		return GameStatus.Waiting(), nil
	case "active":
		return GameStatus.Active(), nil
	case "finished":
		return GameStatus.Finished(), nil
	default:
		return GameStatusEnum{}, fmt.Errorf("unsupported GameStatus value: %q", raw)
	}
}

func ParseGameStatusEmpty(raw string) (*GameStatusEnum, error) {
	if raw == "" {
		return nil, nil
	}

	value, err := ParseGameStatus(raw)
	if err != nil {
		return nil, fmt.Errorf("ParseGameStatus: %w", err)
	}

	return &value, nil
}

func ParseGameStatusOptional(raw *string) (*GameStatusEnum, error) {
	if raw == nil {
		return nil, nil
	}

	value, err := ParseGameStatus(*raw)
	if err != nil {
		return nil, fmt.Errorf("ParseGameStatus: %w", err)
	}

	return &value, nil
}

func (e GameStatusEnum) Is(value GameStatusEnum) bool {
	return value == e
}

func (e GameStatusEnum) Not(value GameStatusEnum) bool {
	return value != e
}

func (e GameStatusEnum) In(values ...GameStatusEnum) bool {
	return slices.Contains(values, e)
}
