// Code generated by genum; DO NOT EDIT.
package enum

import (
	"fmt"
	"slices"
	"strings"
)

type QuestionTypeEnum struct{ enum }

const QuestionType questionType = 0

// questionType выполняет роль пространства имён для значений QuestionTypeEnum.
type questionType int

func (questionType) Standard() QuestionTypeEnum {
	return QuestionTypeEnum{enum{"standard"}}
}

func (questionType) Auction() QuestionTypeEnum {
	return QuestionTypeEnum{enum{"auction"}}
}

func (questionType) CatInBag() QuestionTypeEnum {
	return QuestionTypeEnum{enum{"cat_in_bag"}}
}

func (questionType) NoRisk() QuestionTypeEnum {
	return QuestionTypeEnum{enum{"no_risk"}}
}

var questionTypeValues = []QuestionTypeEnum{ //nolint:gochecknoglobals
	QuestionType.Standard(),
	QuestionType.Auction(),
	QuestionType.CatInBag(),
	QuestionType.NoRisk(),
}

// QuestionTypeValues возвращает перечень всех возможных значений для QuestionTypeEnum.
func QuestionTypeValues() []QuestionTypeEnum {
	return questionTypeValues
}

func ParseQuestionType(raw string) (QuestionTypeEnum, error) {
	switch raw {
	case "standard":
		return QuestionType.Standard(), nil
	case "auction":
		return QuestionType.Auction(), nil
	case "cat_in_bag":
		return QuestionType.CatInBag(), nil
	case "no_risk":
		return QuestionType.NoRisk(), nil
	default:
		return QuestionTypeEnum{}, fmt.Errorf("unsupported QuestionType value: %q", raw)
	}
}

func ParseQuestionTypeFold(raw string) (QuestionTypeEnum, error) {
	switch strings.ToLower(raw) {
	case "standard":
		return QuestionType.Standard(), nil
	case "auction":
		return QuestionType.Auction(), nil
	case "cat_in_bag":
		return QuestionType.CatInBag(), nil
	case "no_risk":
		return QuestionType.NoRisk(), nil
	default:
		return QuestionTypeEnum{}, fmt.Errorf("unsupported QuestionType value: %q", raw)
	}
}

func ParseQuestionTypeEmpty(raw string) (*QuestionTypeEnum, error) {
	if raw == "" {
		return nil, nil
	}

	value, err := ParseQuestionType(raw)
	if err != nil {
		return nil, fmt.Errorf("ParseQuestionType: %w", err)
	}

	return &value, nil
}

func ParseQuestionTypeOptional(raw *string) (*QuestionTypeEnum, error) {
	if raw == nil {
		return nil, nil
	}

	value, err := ParseQuestionType(*raw)
	if err != nil {
		return nil, fmt.Errorf("ParseQuestionType: %w", err)
	}

	return &value, nil
}

func (e QuestionTypeEnum) Is(value QuestionTypeEnum) bool {
	return value == e
}

func (e QuestionTypeEnum) Not(value QuestionTypeEnum) bool {
	return value != e
}

func (e QuestionTypeEnum) In(values ...QuestionTypeEnum) bool {
	return slices.Contains(values, e)
}
