// Code generated by genum; DO NOT EDIT.
package enum

import (
	"fmt"
	"slices"
	"strings"
)

type RoundTypeEnum struct{ enum }

const RoundType roundType = 0

// roundType выполняет роль пространства имён для значений RoundTypeEnum.
type roundType int

func (roundType) Standard() RoundTypeEnum {
	return RoundTypeEnum{enum{"standard"}}
}

func (roundType) Double() RoundTypeEnum {
	return RoundTypeEnum{enum{"double"}}
}

func (roundType) Final() RoundTypeEnum {
	return RoundTypeEnum{enum{"final"}}
}

var roundTypeValues = []RoundTypeEnum{ //nolint:gochecknoglobals
	RoundType.Standard(),
	RoundType.Double(),
	RoundType.Final(),
}

// RoundTypeValues возвращает перечень всех возможных значений для RoundTypeEnum.
func RoundTypeValues() []RoundTypeEnum {
	return roundTypeValues
}

func ParseRoundType(raw string) (RoundTypeEnum, error) {
	switch raw {
	case "standard":
		return RoundType.Standard(), nil
	case "double":
		return RoundType.Double(), nil
	case "final":
		return RoundType.Final(), nil
	default:
		return RoundTypeEnum{}, fmt.Errorf("unsupported RoundType value: %q", raw)
	}
}

func ParseRoundTypeFold(raw string) (RoundTypeEnum, error) {
	switch strings.ToLower(raw) {
	case "standard":
		return RoundType.Standard(), nil
	case "double":
		return RoundType.Double(), nil
	case "final":
		return RoundType.Final(), nil
	default:
		return RoundTypeEnum{}, fmt.Errorf("unsupported RoundType value: %q", raw)
	}
}

func ParseRoundTypeEmpty(raw string) (*RoundTypeEnum, error) {
	if raw == "" {
		return nil, nil
	}

	value, err := ParseRoundType(raw)
	if err != nil {
		return nil, fmt.Errorf("ParseRoundType: %w", err)
	}

	return &value, nil
}

func ParseRoundTypeOptional(raw *string) (*RoundTypeEnum, error) {
	if raw == nil {
		return nil, nil
	}

	value, err := ParseRoundType(*raw)
	if err != nil {
		return nil, fmt.Errorf("ParseRoundType: %w", err)
	}

	return &value, nil
}

func (e RoundTypeEnum) Is(value RoundTypeEnum) bool {
	return value == e
}

func (e RoundTypeEnum) Not(value RoundTypeEnum) bool {
	return value != e
}

func (e RoundTypeEnum) In(values ...RoundTypeEnum) bool {
	return slices.Contains(values, e)
}
